name: Release Images

on:
  schedule:
    - cron: "0 8 * * *" # everyday at 8am UTC
  release:
    types: [published]
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  registry:
    name: Build & Push
    uses: bytefloat/workflows/.github/workflows/docker-build.yml@main
    with:
      custom-image: 'fspnetwork/gallerix'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}